import { describe, expect, it } from "vitest";
import type {
  AdminActionSession,
  Principal,
  Recording,
  TranscriptRevision,
} from "@/domain/models";
import type { CasefileAccessGrant } from "@/server/access/service";
import {
  deriveCasefileCapabilities,
  type CapabilityDenials,
  type CasefileCapabilities,
} from "@/server/casefile/capabilities";

const principals = {
  uploader: {
    userId: "user-uploader",
    email: "uploader@example.com",
    displayName: "Uploader",
    role: "uploader",
  },
  reviewer: {
    userId: "user-reviewer",
    email: "reviewer@example.com",
    displayName: "Reviewer",
    role: "reviewer",
  },
  approver: {
    userId: "user-approver",
    email: "approver@example.com",
    displayName: "Approver",
    role: "approver",
  },
  admin: {
    userId: "user-admin",
    email: "admin@example.com",
    displayName: "Admin",
    role: "admin",
  },
} satisfies Record<string, Principal>;

function buildRecording(overrides: Partial<Recording> = {}): Recording {
  return {
    id: "rec-1",
    workspaceId: "workspace-1",
    title: "Recording 1",
    source: "upload",
    mediaKind: "audio",
    mimeType: "audio/wav",
    mediaPath: null,
    originalFileName: null,
    languageHint: "en",
    transcriptModel: null,
    uploadedByRole: "uploader",
    uploadedByUserId: principals.uploader.userId,
    ingestionSessionId: null,
    transcriptJobId: null,
    integrityState: "verified",
    transcriptJobState: "completed",
    currentRevisionId: "rev-current",
    approvedRevisionId: null,
    pendingRevisionId: null,
    verificationSummary: "Ready",
    createdAt: "2026-08-01T12:00:00.000Z",
    updatedAt: "2026-08-01T12:00:00.000Z",
    automationCursor: null,
    ...overrides,
  };
}

function buildRevision(overrides: Partial<TranscriptRevision> = {}): TranscriptRevision {
  return {
    id: "rev-current",
    recordingId: "rec-1",
    version: 1,
    state: "draft",
    basedOnRevisionId: null,
    createdByRole: "reviewer",
    createdByUserId: principals.reviewer.userId,
    createdAt: "2026-08-01T12:00:00.000Z",
    submittedByUserId: null,
    submittedAt: null,
    approvedAt: null,
    summary: "Revision",
    segments: [],
    ...overrides,
  };
}

function buildActionMode(
  overrides: Partial<Pick<AdminActionSession, "id" | "effectiveRole">> = {},
): Pick<AdminActionSession, "id" | "effectiveRole"> {
  return {
    id: "action-mode-1",
    effectiveRole: "reviewer",
    ...overrides,
  };
}

function buildDenials(overrides: Partial<CapabilityDenials>): CapabilityDenials {
  return {
    canViewStatus: null,
    canViewTranscript: null,
    canViewMedia: null,
    canEdit: null,
    canSave: null,
    canSubmit: null,
    canWithdraw: null,
    canApprove: null,
    canRequestChanges: null,
    canReopen: null,
    canExport: null,
    ...overrides,
  };
}

type CapabilityCase = {
  name: string;
  input: {
    principal: Principal;
    grant: CasefileAccessGrant;
    policyProfileId: "strict" | "reviewable-approved-export";
    recording: Recording;
    revision: TranscriptRevision | null;
    actionMode?: ReturnType<typeof buildActionMode> | null;
    actionModeExpired?: boolean;
  };
  expected: CasefileCapabilities;
};

const capabilityCases = [
    {
      name: "processing active reviewer",
      input: {
        principal: principals.reviewer,
        grant: { kind: "active_reviewer", recordingId: "rec-1", assignmentId: "assignment-1" },
        policyProfileId: "strict",
        recording: buildRecording({ currentRevisionId: null, transcriptJobState: "running" }),
        revision: null,
      },
      expected: {
        canViewStatus: true,
        canViewTranscript: false,
        canViewMedia: true,
        canEdit: false,
        canSave: false,
        canSubmit: false,
        canWithdraw: false,
        canApprove: false,
        canRequestChanges: false,
        canReopen: false,
        canExport: false,
        denials: buildDenials({
          canViewTranscript: "wrong_revision_state",
          canEdit: "wrong_revision_state",
          canSave: "wrong_revision_state",
          canSubmit: "wrong_revision_state",
          canWithdraw: "wrong_revision_state",
          canApprove: "policy",
          canRequestChanges: "policy",
          canReopen: "policy",
          canExport: "policy",
        }),
      },
    },
    {
      name: "draft active reviewer",
      input: {
        principal: principals.reviewer,
        grant: { kind: "active_reviewer", recordingId: "rec-1", assignmentId: "assignment-1" },
        policyProfileId: "strict",
        recording: buildRecording({ currentRevisionId: "rev-draft" }),
        revision: buildRevision({ id: "rev-draft", state: "draft" }),
      },
      expected: {
        canViewStatus: true,
        canViewTranscript: true,
        canViewMedia: true,
        canEdit: true,
        canSave: true,
        canSubmit: true,
        canWithdraw: false,
        canApprove: false,
        canRequestChanges: false,
        canReopen: false,
        canExport: false,
        denials: buildDenials({
          canWithdraw: "wrong_revision_state",
          canApprove: "policy",
          canRequestChanges: "policy",
          canReopen: "policy",
          canExport: "policy",
        }),
      },
    },
    {
      name: "pending active reviewer submitter",
      input: {
        principal: principals.reviewer,
        grant: { kind: "active_reviewer", recordingId: "rec-1", assignmentId: "assignment-1" },
        policyProfileId: "strict",
        recording: buildRecording({ currentRevisionId: "rev-pending", pendingRevisionId: "rev-pending" }),
        revision: buildRevision({
          id: "rev-pending",
          state: "pending_approval",
          submittedByUserId: principals.reviewer.userId,
          submittedAt: "2026-08-01T12:05:00.000Z",
        }),
      },
      expected: {
        canViewStatus: true,
        canViewTranscript: true,
        canViewMedia: true,
        canEdit: false,
        canSave: false,
        canSubmit: false,
        canWithdraw: true,
        canApprove: false,
        canRequestChanges: false,
        canReopen: false,
        canExport: false,
        denials: buildDenials({
          canEdit: "wrong_revision_state",
          canSave: "wrong_revision_state",
          canSubmit: "wrong_revision_state",
          canApprove: "policy",
          canRequestChanges: "policy",
          canReopen: "policy",
          canExport: "policy",
        }),
      },
    },
    {
      name: "pending active approver non-submitter",
      input: {
        principal: principals.approver,
        grant: { kind: "active_approver", recordingId: "rec-1", assignmentId: "assignment-2" },
        policyProfileId: "strict",
        recording: buildRecording({ currentRevisionId: "rev-pending", pendingRevisionId: "rev-pending" }),
        revision: buildRevision({
          id: "rev-pending",
          state: "pending_approval",
          submittedByUserId: principals.reviewer.userId,
          submittedAt: "2026-08-01T12:05:00.000Z",
        }),
      },
      expected: {
        canViewStatus: true,
        canViewTranscript: true,
        canViewMedia: true,
        canEdit: false,
        canSave: false,
        canSubmit: false,
        canWithdraw: false,
        canApprove: true,
        canRequestChanges: true,
        canReopen: false,
        canExport: false,
        denials: buildDenials({
          canEdit: "policy",
          canSave: "policy",
          canSubmit: "policy",
          canWithdraw: "not_submitter",
          canReopen: "wrong_revision_state",
          canExport: "wrong_revision_state",
        }),
      },
    },
    {
      name: "pending active approver with legacy null submitter",
      input: {
        principal: principals.approver,
        grant: { kind: "active_approver", recordingId: "rec-1", assignmentId: "assignment-2" },
        policyProfileId: "strict",
        recording: buildRecording({ currentRevisionId: "rev-pending", pendingRevisionId: "rev-pending" }),
        revision: buildRevision({
          id: "rev-pending",
          state: "pending_approval",
          submittedByUserId: null,
          submittedAt: "2026-08-01T12:05:00.000Z",
        }),
      },
      expected: {
        canViewStatus: true,
        canViewTranscript: true,
        canViewMedia: true,
        canEdit: false,
        canSave: false,
        canSubmit: false,
        canWithdraw: false,
        canApprove: true,
        canRequestChanges: true,
        canReopen: false,
        canExport: false,
        denials: buildDenials({
          canEdit: "policy",
          canSave: "policy",
          canSubmit: "policy",
          canWithdraw: "legacy_submitter_unknown",
          canReopen: "wrong_revision_state",
          canExport: "wrong_revision_state",
        }),
      },
    },
    {
      name: "pending active approver same submitter",
      input: {
        principal: principals.approver,
        grant: { kind: "active_approver", recordingId: "rec-1", assignmentId: "assignment-2" },
        policyProfileId: "strict",
        recording: buildRecording({ currentRevisionId: "rev-pending", pendingRevisionId: "rev-pending" }),
        revision: buildRevision({
          id: "rev-pending",
          state: "pending_approval",
          submittedByUserId: principals.approver.userId,
          submittedAt: "2026-08-01T12:05:00.000Z",
        }),
      },
      expected: {
        canViewStatus: true,
        canViewTranscript: true,
        canViewMedia: true,
        canEdit: false,
        canSave: false,
        canSubmit: false,
        canWithdraw: false,
        canApprove: false,
        canRequestChanges: false,
        canReopen: false,
        canExport: false,
        denials: buildDenials({
          canEdit: "policy",
          canSave: "policy",
          canSubmit: "policy",
          canWithdraw: "not_assigned",
          canApprove: "same_submitter",
          canRequestChanges: "same_submitter",
          canReopen: "wrong_revision_state",
          canExport: "wrong_revision_state",
        }),
      },
    },
    {
      name: "approved active approver strict policy",
      input: {
        principal: principals.approver,
        grant: { kind: "active_approver", recordingId: "rec-1", assignmentId: "assignment-2" },
        policyProfileId: "strict",
        recording: buildRecording({
          currentRevisionId: "rev-approved",
          approvedRevisionId: "rev-approved",
        }),
        revision: buildRevision({
          id: "rev-approved",
          state: "approved",
          submittedByUserId: principals.reviewer.userId,
          approvedAt: "2026-08-01T12:10:00.000Z",
        }),
      },
      expected: {
        canViewStatus: true,
        canViewTranscript: true,
        canViewMedia: true,
        canEdit: false,
        canSave: false,
        canSubmit: false,
        canWithdraw: false,
        canApprove: false,
        canRequestChanges: false,
        canReopen: true,
        canExport: true,
        denials: buildDenials({
          canEdit: "policy",
          canSave: "policy",
          canSubmit: "policy",
          canWithdraw: "wrong_revision_state",
          canApprove: "wrong_revision_state",
          canRequestChanges: "wrong_revision_state",
        }),
      },
    },
    {
      name: "approved active reviewer reviewable export policy",
      input: {
        principal: principals.reviewer,
        grant: { kind: "active_reviewer", recordingId: "rec-1", assignmentId: "assignment-1" },
        policyProfileId: "reviewable-approved-export",
        recording: buildRecording({
          currentRevisionId: "rev-approved",
          approvedRevisionId: "rev-approved",
        }),
        revision: buildRevision({
          id: "rev-approved",
          state: "approved",
          submittedByUserId: principals.reviewer.userId,
          approvedAt: "2026-08-01T12:10:00.000Z",
        }),
      },
      expected: {
        canViewStatus: true,
        canViewTranscript: true,
        canViewMedia: true,
        canEdit: false,
        canSave: false,
        canSubmit: false,
        canWithdraw: false,
        canApprove: false,
        canRequestChanges: false,
        canReopen: false,
        canExport: true,
        denials: buildDenials({
          canEdit: "wrong_revision_state",
          canSave: "wrong_revision_state",
          canSubmit: "wrong_revision_state",
          canWithdraw: "wrong_revision_state",
          canApprove: "policy",
          canRequestChanges: "policy",
          canReopen: "policy",
        }),
      },
    },
    {
      name: "current completed reviewer snapshot under reviewable export policy",
      input: {
        principal: principals.reviewer,
        grant: {
          kind: "completed_reviewer",
          recordingId: "rec-1",
          assignmentId: "assignment-3",
          revisionId: "rev-approved",
        },
        policyProfileId: "reviewable-approved-export",
        recording: buildRecording({
          currentRevisionId: "rev-approved",
          approvedRevisionId: "rev-approved",
        }),
        revision: buildRevision({
          id: "rev-approved",
          state: "approved",
          submittedByUserId: principals.reviewer.userId,
          approvedAt: "2026-08-01T12:10:00.000Z",
        }),
      },
      expected: {
        canViewStatus: true,
        canViewTranscript: true,
        canViewMedia: true,
        canEdit: false,
        canSave: false,
        canSubmit: false,
        canWithdraw: false,
        canApprove: false,
        canRequestChanges: false,
        canReopen: false,
        canExport: true,
        denials: buildDenials({
          canEdit: "wrong_revision_state",
          canSave: "wrong_revision_state",
          canSubmit: "wrong_revision_state",
          canWithdraw: "wrong_revision_state",
          canApprove: "policy",
          canRequestChanges: "policy",
          canReopen: "policy",
        }),
      },
    },
    {
      name: "current completed reviewer snapshot under strict policy",
      input: {
        principal: principals.reviewer,
        grant: {
          kind: "completed_reviewer",
          recordingId: "rec-1",
          assignmentId: "assignment-3",
          revisionId: "rev-approved",
        },
        policyProfileId: "strict",
        recording: buildRecording({
          currentRevisionId: "rev-approved",
          approvedRevisionId: "rev-approved",
        }),
        revision: buildRevision({
          id: "rev-approved",
          state: "approved",
          submittedByUserId: principals.reviewer.userId,
          approvedAt: "2026-08-01T12:10:00.000Z",
        }),
      },
      expected: {
        canViewStatus: true,
        canViewTranscript: true,
        canViewMedia: true,
        canEdit: false,
        canSave: false,
        canSubmit: false,
        canWithdraw: false,
        canApprove: false,
        canRequestChanges: false,
        canReopen: false,
        canExport: false,
        denials: buildDenials({
          canEdit: "wrong_revision_state",
          canSave: "wrong_revision_state",
          canSubmit: "wrong_revision_state",
          canWithdraw: "wrong_revision_state",
          canApprove: "policy",
          canRequestChanges: "policy",
          canReopen: "policy",
          canExport: "policy",
        }),
      },
    },
    {
      name: "historical completed reviewer snapshot",
      input: {
        principal: principals.reviewer,
        grant: {
          kind: "completed_reviewer",
          recordingId: "rec-1",
          assignmentId: "assignment-3",
          revisionId: "rev-old-approved",
        },
        policyProfileId: "reviewable-approved-export",
        recording: buildRecording({
          currentRevisionId: "rev-current",
          approvedRevisionId: "rev-current",
        }),
        revision: buildRevision({
          id: "rev-old-approved",
          state: "approved",
          submittedByUserId: principals.reviewer.userId,
          approvedAt: "2026-08-01T12:10:00.000Z",
        }),
      },
      expected: {
        canViewStatus: true,
        canViewTranscript: true,
        canViewMedia: true,
        canEdit: false,
        canSave: false,
        canSubmit: false,
        canWithdraw: false,
        canApprove: false,
        canRequestChanges: false,
        canReopen: false,
        canExport: false,
        denials: buildDenials({
          canEdit: "historical_snapshot",
          canSave: "historical_snapshot",
          canSubmit: "historical_snapshot",
          canWithdraw: "historical_snapshot",
          canApprove: "historical_snapshot",
          canRequestChanges: "historical_snapshot",
          canReopen: "historical_snapshot",
          canExport: "historical_snapshot",
        }),
      },
    },
    {
      name: "current completed approver snapshot",
      input: {
        principal: principals.approver,
        grant: {
          kind: "completed_approver",
          recordingId: "rec-1",
          assignmentId: "assignment-4",
          revisionId: "rev-approved",
        },
        policyProfileId: "strict",
        recording: buildRecording({
          currentRevisionId: "rev-approved",
          approvedRevisionId: "rev-approved",
        }),
        revision: buildRevision({
          id: "rev-approved",
          state: "approved",
          submittedByUserId: principals.reviewer.userId,
          approvedAt: "2026-08-01T12:10:00.000Z",
        }),
      },
      expected: {
        canViewStatus: true,
        canViewTranscript: true,
        canViewMedia: true,
        canEdit: false,
        canSave: false,
        canSubmit: false,
        canWithdraw: false,
        canApprove: false,
        canRequestChanges: false,
        canReopen: true,
        canExport: true,
        denials: buildDenials({
          canEdit: "policy",
          canSave: "policy",
          canSubmit: "policy",
          canWithdraw: "wrong_revision_state",
          canApprove: "wrong_revision_state",
          canRequestChanges: "wrong_revision_state",
        }),
      },
    },
    {
      name: "historical completed approver snapshot",
      input: {
        principal: principals.approver,
        grant: {
          kind: "completed_approver",
          recordingId: "rec-1",
          assignmentId: "assignment-4",
          revisionId: "rev-old-approved",
        },
        policyProfileId: "strict",
        recording: buildRecording({
          currentRevisionId: "rev-current",
          approvedRevisionId: "rev-current",
        }),
        revision: buildRevision({
          id: "rev-old-approved",
          state: "approved",
          submittedByUserId: principals.reviewer.userId,
          approvedAt: "2026-08-01T12:10:00.000Z",
        }),
      },
      expected: {
        canViewStatus: true,
        canViewTranscript: true,
        canViewMedia: true,
        canEdit: false,
        canSave: false,
        canSubmit: false,
        canWithdraw: false,
        canApprove: false,
        canRequestChanges: false,
        canReopen: false,
        canExport: false,
        denials: buildDenials({
          canEdit: "historical_snapshot",
          canSave: "historical_snapshot",
          canSubmit: "historical_snapshot",
          canWithdraw: "historical_snapshot",
          canApprove: "historical_snapshot",
          canRequestChanges: "historical_snapshot",
          canReopen: "historical_snapshot",
          canExport: "historical_snapshot",
        }),
      },
    },
    {
      name: "uploader status access only",
      input: {
        principal: principals.uploader,
        grant: { kind: "uploader_status", recordingId: "rec-1" },
        policyProfileId: "strict",
        recording: buildRecording({
          currentRevisionId: "rev-approved",
          approvedRevisionId: "rev-approved",
        }),
        revision: buildRevision({
          id: "rev-approved",
          state: "approved",
          submittedByUserId: principals.reviewer.userId,
          approvedAt: "2026-08-01T12:10:00.000Z",
        }),
      },
      expected: {
        canViewStatus: true,
        canViewTranscript: false,
        canViewMedia: false,
        canEdit: false,
        canSave: false,
        canSubmit: false,
        canWithdraw: false,
        canApprove: false,
        canRequestChanges: false,
        canReopen: false,
        canExport: false,
        denials: buildDenials({
          canViewTranscript: "uploader_status_only",
          canViewMedia: "uploader_status_only",
          canEdit: "uploader_status_only",
          canSave: "uploader_status_only",
          canSubmit: "uploader_status_only",
          canWithdraw: "uploader_status_only",
          canApprove: "uploader_status_only",
          canRequestChanges: "uploader_status_only",
          canReopen: "uploader_status_only",
          canExport: "uploader_status_only",
        }),
      },
    },
    {
      name: "admin oversight requires action mode",
      input: {
        principal: principals.admin,
        grant: { kind: "admin_oversight", recordingId: "rec-1" },
        policyProfileId: "strict",
        recording: buildRecording({ currentRevisionId: "rev-draft" }),
        revision: buildRevision({ id: "rev-draft", state: "draft" }),
      },
      expected: {
        canViewStatus: true,
        canViewTranscript: true,
        canViewMedia: true,
        canEdit: false,
        canSave: false,
        canSubmit: false,
        canWithdraw: false,
        canApprove: false,
        canRequestChanges: false,
        canReopen: false,
        canExport: false,
        denials: buildDenials({
          canEdit: "admin_action_mode_required",
          canSave: "admin_action_mode_required",
          canSubmit: "admin_action_mode_required",
          canWithdraw: "admin_action_mode_required",
          canApprove: "admin_action_mode_required",
          canRequestChanges: "admin_action_mode_required",
          canReopen: "admin_action_mode_required",
          canExport: "admin_action_mode_required",
        }),
      },
    },
    {
      name: "admin reviewer action mode on draft",
      input: {
        principal: principals.admin,
        grant: { kind: "admin_oversight", recordingId: "rec-1" },
        policyProfileId: "strict",
        recording: buildRecording({ currentRevisionId: "rev-draft" }),
        revision: buildRevision({ id: "rev-draft", state: "draft" }),
        actionMode: buildActionMode({ effectiveRole: "reviewer" }),
      },
      expected: {
        canViewStatus: true,
        canViewTranscript: true,
        canViewMedia: true,
        canEdit: true,
        canSave: true,
        canSubmit: true,
        canWithdraw: false,
        canApprove: false,
        canRequestChanges: false,
        canReopen: false,
        canExport: false,
        denials: buildDenials({
          canWithdraw: "wrong_revision_state",
          canApprove: "policy",
          canRequestChanges: "policy",
          canReopen: "policy",
          canExport: "policy",
        }),
      },
    },
    {
      name: "admin approver action mode passes the submitter veto (captain ruling 2026-08-06)",
      input: {
        principal: principals.admin,
        grant: { kind: "admin_oversight", recordingId: "rec-1" },
        policyProfileId: "strict",
        recording: buildRecording({ currentRevisionId: "rev-pending", pendingRevisionId: "rev-pending" }),
        revision: buildRevision({
          id: "rev-pending",
          state: "pending_approval",
          submittedByUserId: principals.admin.userId,
          submittedAt: "2026-08-01T12:05:00.000Z",
        }),
        actionMode: buildActionMode({ effectiveRole: "approver" }),
      },
      expected: {
        canViewStatus: true,
        canViewTranscript: true,
        canViewMedia: true,
        canEdit: false,
        canSave: false,
        canSubmit: false,
        canWithdraw: false,
        canApprove: true,
        canRequestChanges: true,
        canReopen: false,
        canExport: false,
        denials: buildDenials({
          canEdit: "policy",
          canSave: "policy",
          canSubmit: "policy",
          canWithdraw: "not_assigned",
          canReopen: "wrong_revision_state",
          canExport: "wrong_revision_state",
        }),
      },
    },
    {
      // Admin ledger access (captain ruling): an admin in reviewer action
      // mode may withdraw a pending revision submitted by someone else; the
      // submitter-only withdrawal rule binds non-admin roles.
      name: "admin reviewer action mode withdraws another user's pending revision",
      input: {
        principal: principals.admin,
        grant: { kind: "admin_oversight", recordingId: "rec-1" },
        policyProfileId: "strict",
        recording: buildRecording({ currentRevisionId: "rev-pending", pendingRevisionId: "rev-pending" }),
        revision: buildRevision({
          id: "rev-pending",
          state: "pending_approval",
          submittedByUserId: principals.reviewer.userId,
          submittedAt: "2026-08-01T12:05:00.000Z",
        }),
        actionMode: buildActionMode({ effectiveRole: "reviewer" }),
      },
      expected: {
        canViewStatus: true,
        canViewTranscript: true,
        canViewMedia: true,
        canEdit: false,
        canSave: false,
        canSubmit: false,
        canWithdraw: true,
        canApprove: false,
        canRequestChanges: false,
        canReopen: false,
        canExport: false,
        denials: buildDenials({
          canEdit: "wrong_revision_state",
          canSave: "wrong_revision_state",
          canSubmit: "wrong_revision_state",
          canApprove: "policy",
          canRequestChanges: "policy",
          canReopen: "policy",
          canExport: "policy",
        }),
      },
    },
    {
      name: "admin oversight without action mode still cannot withdraw another user's pending revision",
      input: {
        principal: principals.admin,
        grant: { kind: "admin_oversight", recordingId: "rec-1" },
        policyProfileId: "strict",
        recording: buildRecording({ currentRevisionId: "rev-pending", pendingRevisionId: "rev-pending" }),
        revision: buildRevision({
          id: "rev-pending",
          state: "pending_approval",
          submittedByUserId: principals.reviewer.userId,
          submittedAt: "2026-08-01T12:05:00.000Z",
        }),
      },
      expected: {
        canViewStatus: true,
        canViewTranscript: true,
        canViewMedia: true,
        canEdit: false,
        canSave: false,
        canSubmit: false,
        canWithdraw: false,
        canApprove: false,
        canRequestChanges: false,
        canReopen: false,
        canExport: false,
        denials: buildDenials({
          canEdit: "admin_action_mode_required",
          canSave: "admin_action_mode_required",
          canSubmit: "admin_action_mode_required",
          canWithdraw: "admin_action_mode_required",
          canApprove: "admin_action_mode_required",
          canRequestChanges: "admin_action_mode_required",
          canReopen: "admin_action_mode_required",
          canExport: "admin_action_mode_required",
        }),
      },
    },
    {
      // Retained boundary: legacy pending revisions without a submitter
      // identity stay un-withdrawable for every role, including an admin in
      // reviewer action mode; they resolve via an approver decision.
      name: "admin reviewer action mode keeps the legacy-submitter withdrawal veto",
      input: {
        principal: principals.admin,
        grant: { kind: "admin_oversight", recordingId: "rec-1" },
        policyProfileId: "strict",
        recording: buildRecording({ currentRevisionId: "rev-pending", pendingRevisionId: "rev-pending" }),
        revision: buildRevision({
          id: "rev-pending",
          state: "pending_approval",
          submittedByUserId: null,
          submittedAt: "2026-08-01T12:05:00.000Z",
        }),
        actionMode: buildActionMode({ effectiveRole: "reviewer" }),
      },
      expected: {
        canViewStatus: true,
        canViewTranscript: true,
        canViewMedia: true,
        canEdit: false,
        canSave: false,
        canSubmit: false,
        canWithdraw: false,
        canApprove: false,
        canRequestChanges: false,
        canReopen: false,
        canExport: false,
        denials: buildDenials({
          canEdit: "wrong_revision_state",
          canSave: "wrong_revision_state",
          canSubmit: "wrong_revision_state",
          canWithdraw: "legacy_submitter_unknown",
          canApprove: "policy",
          canRequestChanges: "policy",
          canReopen: "policy",
          canExport: "policy",
        }),
      },
    },
    {
      name: "admin approver action mode decides a legacy pending revision",
      input: {
        principal: principals.admin,
        grant: { kind: "admin_oversight", recordingId: "rec-1" },
        policyProfileId: "strict",
        recording: buildRecording({ currentRevisionId: "rev-pending", pendingRevisionId: "rev-pending" }),
        revision: buildRevision({
          id: "rev-pending",
          state: "pending_approval",
          submittedByUserId: null,
          submittedAt: "2026-08-01T12:05:00.000Z",
        }),
        actionMode: buildActionMode({ effectiveRole: "approver" }),
      },
      expected: {
        canViewStatus: true,
        canViewTranscript: true,
        canViewMedia: true,
        canEdit: false,
        canSave: false,
        canSubmit: false,
        canWithdraw: false,
        canApprove: true,
        canRequestChanges: true,
        canReopen: false,
        canExport: false,
        denials: buildDenials({
          canEdit: "policy",
          canSave: "policy",
          canSubmit: "policy",
          canWithdraw: "legacy_submitter_unknown",
          canReopen: "wrong_revision_state",
          canExport: "wrong_revision_state",
        }),
      },
    },
    {
      name: "admin historical oversight stays historical before action mode required",
      input: {
        principal: principals.admin,
        grant: { kind: "admin_oversight", recordingId: "rec-1" },
        policyProfileId: "strict",
        recording: buildRecording({
          currentRevisionId: "rev-current",
          approvedRevisionId: "rev-current",
        }),
        revision: buildRevision({
          id: "rev-old-approved",
          state: "approved",
          submittedByUserId: principals.reviewer.userId,
          approvedAt: "2026-08-01T12:10:00.000Z",
        }),
      },
      expected: {
        canViewStatus: true,
        canViewTranscript: true,
        canViewMedia: true,
        canEdit: false,
        canSave: false,
        canSubmit: false,
        canWithdraw: false,
        canApprove: false,
        canRequestChanges: false,
        canReopen: false,
        canExport: false,
        denials: buildDenials({
          canEdit: "historical_snapshot",
          canSave: "historical_snapshot",
          canSubmit: "historical_snapshot",
          canWithdraw: "historical_snapshot",
          canApprove: "historical_snapshot",
          canRequestChanges: "historical_snapshot",
          canReopen: "historical_snapshot",
          canExport: "historical_snapshot",
        }),
      },
    },
    {
      name: "admin expired action mode denial wins over required or state",
      input: {
        principal: principals.admin,
        grant: { kind: "admin_oversight", recordingId: "rec-1" },
        policyProfileId: "strict",
        recording: buildRecording({
          currentRevisionId: "rev-approved",
          approvedRevisionId: "rev-approved",
        }),
        revision: buildRevision({
          id: "rev-approved",
          state: "approved",
          submittedByUserId: principals.reviewer.userId,
          approvedAt: "2026-08-01T12:10:00.000Z",
        }),
        actionModeExpired: true,
      },
      expected: {
        canViewStatus: true,
        canViewTranscript: true,
        canViewMedia: true,
        canEdit: false,
        canSave: false,
        canSubmit: false,
        canWithdraw: false,
        canApprove: false,
        canRequestChanges: false,
        canReopen: false,
        canExport: false,
        denials: buildDenials({
          canEdit: "admin_action_mode_expired",
          canSave: "admin_action_mode_expired",
          canSubmit: "admin_action_mode_expired",
          canWithdraw: "admin_action_mode_expired",
          canApprove: "admin_action_mode_expired",
          canRequestChanges: "admin_action_mode_expired",
          canReopen: "admin_action_mode_expired",
          canExport: "admin_action_mode_expired",
        }),
      },
    },
] satisfies CapabilityCase[];

type ForgedActionModeCase = {
  name: string;
  input: CapabilityCase["input"];
  expectedFlags: Pick<
    CasefileCapabilities,
    | "canEdit"
    | "canSave"
    | "canSubmit"
    | "canApprove"
    | "canRequestChanges"
    | "canExport"
  >;
  expectedDenials: Partial<CapabilityDenials>;
};

const forgedActionModeCases = [
  {
    name: "ignores forged approver mode for a reviewer principal in admin oversight",
    input: {
      principal: principals.reviewer,
      grant: { kind: "admin_oversight", recordingId: "rec-1" },
      policyProfileId: "strict",
      recording: buildRecording({ currentRevisionId: "rev-pending", pendingRevisionId: "rev-pending" }),
      revision: buildRevision({
        id: "rev-pending",
        state: "pending_approval",
        submittedByUserId: principals.uploader.userId,
        submittedAt: "2026-08-01T12:05:00.000Z",
      }),
      actionMode: buildActionMode({ effectiveRole: "approver" }),
    },
    expectedFlags: {
      canEdit: false,
      canSave: false,
      canSubmit: false,
      canApprove: false,
      canRequestChanges: false,
      canExport: false,
    },
    expectedDenials: {
      canApprove: "policy",
      canRequestChanges: "policy",
    },
  },
  {
    name: "ignores forged approver mode for a reviewer assignment",
    input: {
      principal: principals.reviewer,
      grant: { kind: "active_reviewer", recordingId: "rec-1", assignmentId: "assignment-1" },
      policyProfileId: "strict",
      recording: buildRecording({ currentRevisionId: "rev-pending", pendingRevisionId: "rev-pending" }),
      revision: buildRevision({
        id: "rev-pending",
        state: "pending_approval",
        submittedByUserId: principals.uploader.userId,
        submittedAt: "2026-08-01T12:05:00.000Z",
      }),
      actionMode: buildActionMode({ effectiveRole: "approver" }),
    },
    expectedFlags: {
      canEdit: false,
      canSave: false,
      canSubmit: false,
      canApprove: false,
      canRequestChanges: false,
      canExport: false,
    },
    expectedDenials: {
      canApprove: "policy",
      canRequestChanges: "policy",
    },
  },
  {
    name: "ignores forged approver mode for an admin without oversight grant",
    input: {
      principal: principals.admin,
      grant: { kind: "active_reviewer", recordingId: "rec-1", assignmentId: "assignment-1" },
      policyProfileId: "strict",
      recording: buildRecording({ currentRevisionId: "rev-pending", pendingRevisionId: "rev-pending" }),
      revision: buildRevision({
        id: "rev-pending",
        state: "pending_approval",
        submittedByUserId: principals.uploader.userId,
        submittedAt: "2026-08-01T12:05:00.000Z",
      }),
      actionMode: buildActionMode({ effectiveRole: "approver" }),
    },
    expectedFlags: {
      canEdit: false,
      canSave: false,
      canSubmit: false,
      canApprove: false,
      canRequestChanges: false,
      canExport: false,
    },
    expectedDenials: {
      canApprove: "policy",
      canRequestChanges: "policy",
    },
  },
  {
    name: "ignores forged reviewer mode when the oversight grant points at another recording",
    input: {
      principal: principals.admin,
      grant: { kind: "admin_oversight", recordingId: "rec-other" },
      policyProfileId: "strict",
      recording: buildRecording({ currentRevisionId: "rev-draft" }),
      revision: buildRevision({ id: "rev-draft", state: "draft" }),
      actionMode: buildActionMode({ effectiveRole: "reviewer" }),
    },
    expectedFlags: {
      canEdit: false,
      canSave: false,
      canSubmit: false,
      canApprove: false,
      canRequestChanges: false,
      canExport: false,
    },
    expectedDenials: {
      canEdit: "policy",
      canSave: "policy",
      canSubmit: "policy",
    },
  },
] satisfies ForgedActionModeCase[];

describe("deriveCasefileCapabilities", () => {
  it.each(capabilityCases)("$name", ({ input, expected }) => {
    expect(deriveCasefileCapabilities(input)).toEqual(expected);
  });

  it.each(forgedActionModeCases)("$name", ({ input, expectedFlags, expectedDenials }) => {
    const actual = deriveCasefileCapabilities(input);

    expect(actual).toEqual(expect.objectContaining(expectedFlags));
    expect(actual.denials).toEqual(expect.objectContaining(expectedDenials));
  });
});
