import type { TranscriptRevision } from "@/domain/models";

export const baseSegments: TranscriptRevision["segments"] = [
  {
    id: "seg-1",
    speakerLabel: "Speaker 1",
    startMs: 0,
    endMs: 10_000,
    text: "Hello world.",
    confidence: 0.91,
  },
  {
    id: "seg-2",
    speakerLabel: "Speaker 2",
    startMs: 10_000,
    endMs: 20_000,
    text: "General Kenobi.",
    confidence: 0.83,
  },
];

export function createCasefile(overrides: Record<string, unknown> = {}) {
  return {
    statusOnly: false,
    recordingId: "rec-1",
    workspaceId: "workspace-1",
    title: "Governed recording",
    source: "upload",
    sourceLabel: "Upload",
    stage: "draft_review",
    stageLabel: "Draft review",
    updatedAt: "2026-08-01T12:00:00.000Z",
    updatedAtLabel: "01 Aug 2026, 12:00 UTC",
    updatedAtIso: "2026-08-01T12:00:00.000Z",
    assignmentLabel: "Assigned to you",
    historicalLabel: null,
    access: {
      kind: "active_reviewer",
      recordingId: "rec-1",
      assignmentId: "assign-1",
      historical: false,
    },
    actionMode: null,
    adminActionModeOptions: [],
    capabilities: {
      canViewStatus: true,
      canViewTranscript: true,
      canViewMedia: true,
      canEdit: true,
      canSave: true,
      canSubmit: true,
      canWithdraw: false,
      canApprove: false,
      canRequestChanges: false,
      canReopen: false,
      canExport: false,
      denials: {
        canViewStatus: null,
        canViewTranscript: null,
        canViewMedia: null,
        canEdit: null,
        canSave: null,
        canSubmit: null,
        canWithdraw: "wrong_revision_state",
        canApprove: "wrong_revision_state",
        canRequestChanges: "wrong_revision_state",
        canReopen: "wrong_revision_state",
        canExport: "wrong_revision_state",
      },
    },
    media: {
      kind: "audio",
      url: "/api/media/rec-1",
      denialReason: null,
    },
    processing: {
      active: false,
      integrityState: "verified",
      transcriptJobState: "completed",
      progressPercent: null,
      etaSeconds: null,
      verificationSummary: "Ready for review.",
      recoveryHint: null,
    },
    provenance: {
      languageHint: "en",
      originalFileName: "governed.wav",
      verificationSummary: "Ready for review.",
    },
    policy: {
      mediaAccessLabel: "Allowed",
      transcriptExportLabel: "Blocked until approval",
      draftEditLabel: "Allowed",
      approvalLabel: "Reviewer submits for approval",
      reopenLabel: "Approver only",
    },
    assignments: [
      {
        id: "assign-1",
        userDisplay: "Reviewer Example",
        assignmentRole: "reviewer",
        status: "active",
        createdAtLabel: "01 Aug 2026, 11:00 UTC",
        endedAtLabel: null,
        completedRevisionLabel: null,
      },
    ],
    revision: {
      id: "rev-1",
      version: 1,
      state: "draft",
      stateLabel: "Draft",
      summary: "Ready for review.",
      createdAt: "2026-08-01T12:00:00.000Z",
      createdAtLabel: "01 Aug 2026, 12:00 UTC",
      createdAtIso: "2026-08-01T12:00:00.000Z",
      submittedAt: null,
      approvedAt: null,
      submittedByDisplay: null,
      basedOnRevisionId: null,
      segments: baseSegments,
    },
    revisions: [
      {
        id: "rev-1",
        version: 1,
        state: "draft",
        stateLabel: "Draft",
        summary: "Ready for review.",
        createdAt: "2026-08-01T12:00:00.000Z",
        createdAtLabel: "01 Aug 2026, 12:00 UTC",
        createdAtIso: "2026-08-01T12:00:00.000Z",
        submittedAt: null,
        approvedAt: null,
        submittedByDisplay: null,
      },
    ],
    decisions: [],
    audit: [],
    nextActions: [
      { capability: "canEdit", label: "Continue editing" },
      { capability: "canSubmit", label: "Submit for approval" },
    ],
    ...overrides,
  } as any;
}
