import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

// Sidebar for the staged docs corpus (website/content/, generated by
// scripts/stage-docs.sh from README.md, DESIGN.md, CONTRIBUTING.md,
// docs/USER-GUIDE.md, docs/operators/, ...). Internal artifacts (TODOS.md,
// docs/operators/oidc-acceptance-2026-08.md) are deliberately not staged.
const sidebars: SidebarsConfig = {
  docs: [
    {
      type: 'doc',
      id: 'index',
      label: 'Superscriber',
    },
    'USER-GUIDE',
    'DESIGN',
    'CONTRIBUTING',
    {
      type: 'category',
      label: 'Operator runbooks',
      items: [
        'operators/authentik-oidc',
        'operators/identity-linking',
        'operators/key-and-certificate-rotation',
        'operators/no-mail-profile',
        'operators/password-reset',
        'operators/auth-outage',
        'operators/auth-rollback',
        'operators/break-glass',
        'operators/admin-recovery',
        'operators/ingest-watch',
        'operators/diarization',
      ],
    },
    'CHANGELOG',
  ],
};

export default sidebars;
