import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

// Sidebar for the staged docs corpus (website/content/, generated by
// scripts/stage-docs.sh from README.md, DESIGN.md, docs/operators/, ...).
// Future user guide: when the demo lane lands docs/USER-GUIDE.md the staging
// script picks it up automatically - add 'USER-GUIDE' below at that point.
const sidebars: SidebarsConfig = {
  docs: [
    {
      type: 'doc',
      id: 'index',
      label: 'Superscriber',
    },
    'DESIGN',
    {
      type: 'category',
      label: 'Operator runbooks',
      items: [
        'operators/authentik-oidc',
        'operators/identity-linking',
        'operators/key-and-certificate-rotation',
        'operators/no-mail-profile',
        'operators/password-reset',
        'operators/auth-outage',
        'operators/auth-rollback',
        'operators/break-glass',
        'operators/oidc-acceptance-2026-08',
        'operators/ingest-watch',
      ],
    },
    'CHANGELOG',
    'TODOS',
  ],
};

export default sidebars;
